feat: update icons based on HugeIcons
AtB-AS/design-system pull request #258
Opened 2024-12-11 11:35 UTC by reidzeibel

Updates various icons in the app based on HugeIcons design, done in collaboration with @Aliaaen

2024-12-16 14:14 UTC, Aliaaen requested changes

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/profile/User.svg
![User](https://github.com/user-attachments/assets/14310dd7-09ad-41f6-9cdd-c2c02647ca8c)
 Swap :)

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/tab-bar/profile.svg
![profile](https://github.com/user-attachments/assets/7248c2e3-3920-4bf8-9be5-95afcf593a7e)
Swap :)

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/places/Favorite.svg
![Favorite](https://github.com/user-attachments/assets/be0da604-ee1d-48e0-877d-d097af409e7b)
Swap :)

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/places/FavoriteDisable.svg
![FavoriteDisable](https://github.com/user-attachments/assets/1cc8ab77-bb5d-4982-8d7b-75a35f012bc2)
Swap :)

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/places/FavoriteFill.svg
![FavoriteFill](https://github.com/user-attachments/assets/4f80645f-3fa4-4304-8a95-817795ad80e2)
Swap and resize! :)

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/places/FavoriteSemi.svg
![FavoriteSemi](https://github.com/user-attachments/assets/38026624-dbc1-4faa-a093-d24127a78f0a)
Swap :)

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/vehicles/Battery.svg
Needs a resize, but the new icon doesn't fit into the same proportions... 🤔

2024-12-16 14:14 UTC, Aliaaen commented on packages/assets/files/common/mono/vehicles/Bicycle.svg
Needs a resize, but I'm not sure if the new icon fits into the same proportions... 🤔

2024-12-17 13:14 UTC, reidzeibel commented on packages/assets/files/nfk/colors/icons/status/dark/Info.svg
done

2024-12-17 13:14 UTC, reidzeibel commented on packages/assets/files/nfk/colors/icons/status/dark/Warning.svg
done

2024-12-17 13:15 UTC, reidzeibel commented on packages/assets/files/troms/colors/icons/status/dark/Check.svg
done

2024-12-17 13:15 UTC, reidzeibel commented on packages/assets/files/troms/colors/icons/status/dark/Error.svg
done

2024-12-17 13:23 UTC, reidzeibel commented on packages/assets/files/common/mono/navigation/BusLiveArrow.svg
The old one doesn't have any fill colors, I think the colors get added based on the app theme colors, I think we can just use what we have now and then fix it as needed. No worries :)

2024-12-17 13:30 UTC, reidzeibel commented on packages/assets/files/common/colors/icons/ticketing/Seats.svg
reverted

2024-12-17 13:30 UTC, reidzeibel commented on packages/assets/files/common/colors/icons/ticketing/Visa.svg
reverted

2025-01-13 11:47 UTC, rosvik approved these changes
<img width="300px" src="https://github.com/user-attachments/assets/df4a74f5-db4f-4e90-b74b-3fa7d9eba93a">

2025-01-13 11:49 UTC, merged